import { initDB, indexedDB } from './db'
import { createLocalId } from './localId'

/** A persisted message in the independent AI assistant workspace. */
export type AssistantMessageRole = 'user' | 'assistant' | 'system'

export interface AssistantMessage {
  id: string
  role: AssistantMessageRole
  content: string
  createdAt: number
}

export interface AssistantAttachment {
  id: string
  fileName: string
  fileType: string
  content: string
  originalCharCount?: number
  createdAt: number
}

/**
 * Sessions intentionally keep only the selected book id. Book details and
 * learning records are resolved when a request mentions that book, so stale
 * snapshots do not accumulate in local storage or in the model context.
 */
export interface AssistantSession {
  id: string
  title: string
  bookId?: string
  messages: AssistantMessage[]
  attachments: AssistantAttachment[]
  /** Optional rolling summary generated by the caller to reduce prompt size. */
  summary?: string
  createdAt: number
  updatedAt: number
}

export interface CreateAssistantSessionInput {
  title?: string
  bookId?: string
}

export interface AppendAssistantMessageInput {
  role: AssistantMessageRole
  content: string
  createdAt?: number
}

export interface AddAssistantAttachmentInput {
  fileName: string
  fileType: string
  content: string
  originalCharCount?: number
  createdAt?: number
}

export const ASSISTANT_SESSIONS_METADATA_KEY = 'assistant-sessions'
export const MAX_ASSISTANT_ATTACHMENTS = 5
export const MAX_ASSISTANT_ATTACHMENT_CHARS = 12000
export const MAX_ASSISTANT_ATTACHMENT_TOTAL_CHARS = 30000
const DEFAULT_SESSION_TITLE = '新会话'

let writeQueue: Promise<void> = Promise.resolve()

function clone<T>(value: T): T {
  return typeof structuredClone === 'function'
    ? structuredClone(value)
    : JSON.parse(JSON.stringify(value)) as T
}

function isMessageRole(value: unknown): value is AssistantMessageRole {
  return value === 'user' || value === 'assistant' || value === 'system'
}

function normalizeMessage(value: unknown): AssistantMessage | null {
  if (!value || typeof value !== 'object') return null
  const candidate = value as Partial<AssistantMessage>
  if (typeof candidate.id !== 'string' || !isMessageRole(candidate.role) || typeof candidate.content !== 'string') {
    return null
  }
  const content = candidate.content.trim()
  if (!content) return null
  return {
    id: candidate.id,
    role: candidate.role,
    content,
    createdAt: typeof candidate.createdAt === 'number' && Number.isFinite(candidate.createdAt)
      ? candidate.createdAt
      : Date.now()
  }
}

function normalizeAttachments(value: unknown): AssistantAttachment[] {
  if (!Array.isArray(value)) return []
  const attachments: AssistantAttachment[] = []
  let remainingChars = MAX_ASSISTANT_ATTACHMENT_TOTAL_CHARS

  for (const item of value) {
    if (attachments.length >= MAX_ASSISTANT_ATTACHMENTS || remainingChars <= 0) break
    if (!item || typeof item !== 'object') continue
    const candidate = item as Partial<AssistantAttachment>
    if (
      typeof candidate.id !== 'string' ||
      typeof candidate.fileName !== 'string' ||
      typeof candidate.fileType !== 'string' ||
      typeof candidate.content !== 'string'
    ) continue
    const fileName = candidate.fileName.trim()
    const fileType = candidate.fileType.trim()
    const content = candidate.content.trim().slice(
      0,
      Math.min(MAX_ASSISTANT_ATTACHMENT_CHARS, remainingChars)
    )
    if (!fileName || !fileType || !content) continue
    attachments.push({
      id: candidate.id,
      fileName,
      fileType,
      content,
      ...(typeof candidate.originalCharCount === 'number' && Number.isFinite(candidate.originalCharCount) && candidate.originalCharCount >= content.length
        ? { originalCharCount: Math.floor(candidate.originalCharCount) }
        : {}),
      createdAt: typeof candidate.createdAt === 'number' && Number.isFinite(candidate.createdAt)
        ? candidate.createdAt
        : Date.now()
    })
    remainingChars -= content.length
  }
  return attachments
}

function validateAttachments(value: AssistantAttachment[]): AssistantAttachment[] {
  if (value.length > MAX_ASSISTANT_ATTACHMENTS) throw new Error('ASSISTANT_ATTACHMENT_LIMIT_REACHED')
  const totalChars = value.reduce((sum, attachment) => sum + (typeof attachment.content === 'string'
    ? attachment.content.trim().length
    : 0), 0)
  if (totalChars > MAX_ASSISTANT_ATTACHMENT_TOTAL_CHARS) throw new Error('ASSISTANT_ATTACHMENT_TOTAL_TOO_LARGE')
  const normalized = normalizeAttachments(value)
  if (normalized.length !== value.length) throw new Error('ASSISTANT_ATTACHMENT_INVALID')
  if (value.some((attachment, index) => attachment.content.trim().length > MAX_ASSISTANT_ATTACHMENT_CHARS ||
    normalized[index].content.length !== attachment.content.trim().length)) {
    throw new Error('ASSISTANT_ATTACHMENT_TOO_LARGE')
  }
  return normalized
}

function normalizeSession(value: unknown): AssistantSession | null {
  if (!value || typeof value !== 'object') return null
  const candidate = value as Partial<AssistantSession>
  if (typeof candidate.id !== 'string' || typeof candidate.title !== 'string') return null
  const messages = Array.isArray(candidate.messages)
    ? candidate.messages.map(normalizeMessage).filter((message): message is AssistantMessage => message !== null)
    : []
  const attachments = normalizeAttachments(candidate.attachments)
  const createdAt = typeof candidate.createdAt === 'number' && Number.isFinite(candidate.createdAt)
    ? candidate.createdAt
    : Date.now()
  const updatedAt = typeof candidate.updatedAt === 'number' && Number.isFinite(candidate.updatedAt)
    ? candidate.updatedAt
    : createdAt
  const bookId = typeof candidate.bookId === 'string' && candidate.bookId.trim() ? candidate.bookId : undefined
  const summary = typeof candidate.summary === 'string' && candidate.summary.trim()
    ? candidate.summary.trim()
    : undefined
  return {
    id: candidate.id,
    title: candidate.title.trim() || DEFAULT_SESSION_TITLE,
    ...(bookId ? { bookId } : {}),
    messages,
    attachments,
    ...(summary ? { summary } : {}),
    createdAt,
    updatedAt
  }
}

function sortSessions(sessions: AssistantSession[]): AssistantSession[] {
  return sessions.slice().sort((a, b) => b.updatedAt - a.updatedAt)
}

async function readSessions(): Promise<AssistantSession[]> {
  await initDB()
  const record = await indexedDB.get<{ key: string; sessions?: unknown }>('metadata', ASSISTANT_SESSIONS_METADATA_KEY)
  if (!record || !Array.isArray(record.sessions)) return []
  return sortSessions(record.sessions.map(normalizeSession).filter((session): session is AssistantSession => session !== null))
}

async function writeSessions(sessions: AssistantSession[]): Promise<void> {
  await initDB()
  await indexedDB.put('metadata', {
    key: ASSISTANT_SESSIONS_METADATA_KEY,
    sessions: sortSessions(sessions).map(clone)
  })
}

function queueWrite(operation: () => Promise<void>): Promise<void> {
  writeQueue = writeQueue.then(operation, operation)
  return writeQueue
}

export async function getAssistantSessions(): Promise<AssistantSession[]> {
  return clone(await readSessions())
}

export async function createAssistantSession(input: CreateAssistantSessionInput = {}): Promise<AssistantSession> {
  const now = Date.now()
  const session: AssistantSession = {
    id: createLocalId(),
    title: input.title?.trim() || DEFAULT_SESSION_TITLE,
    ...(input.bookId?.trim() ? { bookId: input.bookId.trim() } : {}),
    messages: [],
    attachments: [],
    createdAt: now,
    updatedAt: now
  }
  await queueWrite(async () => {
    const sessions = await readSessions()
    await writeSessions([session, ...sessions])
  })
  return clone(session)
}

export async function updateAssistantSession(
  id: string,
  updates: Partial<Pick<AssistantSession, 'title' | 'bookId' | 'summary' | 'attachments'>>
): Promise<AssistantSession> {
  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    const title = updates.title === undefined ? existing.title : updates.title.trim() || DEFAULT_SESSION_TITLE
    const next: AssistantSession = {
      ...existing,
      title,
      ...(updates.bookId === undefined
        ? (existing.bookId ? { bookId: existing.bookId } : {})
        : (updates.bookId.trim() ? { bookId: updates.bookId.trim() } : {})),
      ...(updates.summary === undefined
        ? (existing.summary ? { summary: existing.summary } : {})
        : (updates.summary.trim() ? { summary: updates.summary.trim() } : {})),
      attachments: updates.attachments === undefined
        ? existing.attachments
        : validateAttachments(updates.attachments),
      updatedAt: Date.now()
    }
    result = next
    await writeSessions(sessions.map(session => session.id === id ? next : session))
  })
  return clone(result as AssistantSession)
}

export async function appendAssistantMessage(
  id: string,
  input: AppendAssistantMessageInput
): Promise<AssistantSession> {
  const content = input.content.trim()
  if (!isMessageRole(input.role)) throw new Error('ASSISTANT_MESSAGE_ROLE_INVALID')
  if (!content) throw new Error('ASSISTANT_MESSAGE_EMPTY')

  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    const message: AssistantMessage = {
      id: createLocalId(),
      role: input.role,
      content,
      createdAt: typeof input.createdAt === 'number' && Number.isFinite(input.createdAt)
        ? input.createdAt
        : Date.now()
    }
    result = { ...existing, messages: [...existing.messages, message], updatedAt: Date.now() }
    await writeSessions(sessions.map(session => session.id === id ? result as AssistantSession : session))
  })
  return clone(result as AssistantSession)
}

export async function addAssistantAttachment(
  id: string,
  input: AddAssistantAttachmentInput
): Promise<AssistantSession> {
  const fileName = input.fileName.trim()
  const fileType = input.fileType.trim()
  const content = input.content.trim()
  if (!fileName || !fileType || !content) throw new Error('ASSISTANT_ATTACHMENT_INVALID')
  if (content.length > MAX_ASSISTANT_ATTACHMENT_CHARS) throw new Error('ASSISTANT_ATTACHMENT_TOO_LARGE')

  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    if (existing.attachments.length >= MAX_ASSISTANT_ATTACHMENTS) {
      throw new Error('ASSISTANT_ATTACHMENT_LIMIT_REACHED')
    }
    const totalChars = existing.attachments.reduce((sum, attachment) => sum + attachment.content.length, 0)
    if (totalChars + content.length > MAX_ASSISTANT_ATTACHMENT_TOTAL_CHARS) {
      throw new Error('ASSISTANT_ATTACHMENT_TOTAL_TOO_LARGE')
    }
    const attachment: AssistantAttachment = {
      id: createLocalId(),
      fileName,
      fileType,
      content,
      ...(typeof input.originalCharCount === 'number' && Number.isFinite(input.originalCharCount) && input.originalCharCount >= content.length
        ? { originalCharCount: Math.floor(input.originalCharCount) }
        : {}),
      createdAt: typeof input.createdAt === 'number' && Number.isFinite(input.createdAt)
        ? input.createdAt
        : Date.now()
    }
    result = {
      ...existing,
      attachments: [...existing.attachments, attachment],
      updatedAt: Date.now()
    }
    await writeSessions(sessions.map(session => session.id === id ? result as AssistantSession : session))
  })
  return clone(result as AssistantSession)
}

export async function removeAssistantAttachment(id: string, attachmentId: string): Promise<AssistantSession> {
  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    if (!existing.attachments.some(attachment => attachment.id === attachmentId)) {
      throw new Error(`ASSISTANT_ATTACHMENT_NOT_FOUND:${attachmentId}`)
    }
    result = {
      ...existing,
      attachments: existing.attachments.filter(attachment => attachment.id !== attachmentId),
      updatedAt: Date.now()
    }
    await writeSessions(sessions.map(session => session.id === id ? result as AssistantSession : session))
  })
  return clone(result as AssistantSession)
}

/** Remove a user message and everything after it so it can be edited and resent. */
export async function truncateAssistantMessages(id: string, messageId: string): Promise<AssistantSession> {
  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    const messageIndex = existing.messages.findIndex(message => message.id === messageId)
    if (messageIndex < 0) throw new Error(`ASSISTANT_MESSAGE_NOT_FOUND:${messageId}`)
    result = {
      ...existing,
      messages: existing.messages.slice(0, messageIndex),
      updatedAt: Date.now()
    }
    await writeSessions(sessions.map(session => session.id === id ? result as AssistantSession : session))
  })
  return clone(result as AssistantSession)
}

/** Create an independent conversation branch ending at a selected message. */
export async function createAssistantBranchSession(id: string, messageId: string, title?: string): Promise<AssistantSession> {
  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    const messageIndex = existing.messages.findIndex(message => message.id === messageId)
    if (messageIndex < 0) throw new Error(`ASSISTANT_MESSAGE_NOT_FOUND:${messageId}`)
    const now = Date.now()
    result = {
      ...clone(existing),
      id: createLocalId(),
      title: title?.trim() || `${existing.title} · 分支`,
      messages: existing.messages.slice(0, messageIndex + 1).map(clone),
      createdAt: now,
      updatedAt: now
    }
    await writeSessions([result, ...sessions])
  })
  return clone(result as AssistantSession)
}

export async function deleteAssistantSession(id: string): Promise<void> {
  await queueWrite(async () => {
    const sessions = await readSessions()
    await writeSessions(sessions.filter(session => session.id !== id))
  })
}

export async function clearAssistantSessions(): Promise<void> {
  await queueWrite(() => writeSessions([]))
}

/**
 * Keep a compact, message-boundary-safe history for a model request. The
 * persisted conversation remains complete; this only limits the prompt.
 */
export function compactAssistantHistory(messages: AssistantMessage[], maxChars = 12000): AssistantMessage[] {
  if (maxChars <= 0) return []
  const compacted: AssistantMessage[] = []
  let used = 0
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index]
    const cost = message.content.length
    if (compacted.length > 0 && used + cost > maxChars) break
    if (cost > maxChars && compacted.length === 0) {
      compacted.unshift({ ...message, content: message.content.slice(-maxChars) })
      break
    }
    compacted.unshift(message)
    used += cost
  }
  return clone(compacted)
}

export interface CompactAssistantContext {
  messages: AssistantMessage[]
  summary: string
  omittedCount: number
}

/**
 * Keep the newest complete messages and make a small local summary of older
 * turns. This avoids a second model call while keeping the prompt bounded.
 */
export function compactAssistantContext(messages: AssistantMessage[], maxChars = 12000): CompactAssistantContext {
  const recentBudget = Math.max(1, Math.floor(maxChars * 0.78))
  const recent = compactAssistantHistory(messages, recentBudget)
  const omittedCount = Math.max(0, messages.length - recent.length)
  if (!omittedCount) return { messages: recent, summary: '', omittedCount: 0 }

  const older = messages.slice(0, omittedCount)
  const summary = older
    .map(message => `${message.role === 'user' ? '用户' : '助手'}：${message.content.replace(/\s+/g, ' ').trim()}`)
    .join('\n')
    .slice(-Math.min(2_400, Math.max(600, Math.floor(maxChars * 0.2))))
  return { messages: recent, summary, omittedCount }
}
