import { initDB, indexedDB } from './db'
import { createLocalId } from './localId'

/** A persisted message in the independent AI assistant workspace. */
export type AssistantMessageRole = 'user' | 'assistant' | 'system'

export interface AssistantMessage {
  id: string
  role: AssistantMessageRole
  content: string
  createdAt: number
}

/**
 * Sessions intentionally keep only the selected book id. Book details and
 * learning records are resolved when a request mentions that book, so stale
 * snapshots do not accumulate in local storage or in the model context.
 */
export interface AssistantSession {
  id: string
  title: string
  bookId?: string
  messages: AssistantMessage[]
  /** Optional rolling summary generated by the caller to reduce prompt size. */
  summary?: string
  createdAt: number
  updatedAt: number
}

export interface CreateAssistantSessionInput {
  title?: string
  bookId?: string
}

export interface AppendAssistantMessageInput {
  role: AssistantMessageRole
  content: string
  createdAt?: number
}

export const ASSISTANT_SESSIONS_METADATA_KEY = 'assistant-sessions'
const DEFAULT_SESSION_TITLE = '新会话'

let writeQueue: Promise<void> = Promise.resolve()

function clone<T>(value: T): T {
  return typeof structuredClone === 'function'
    ? structuredClone(value)
    : JSON.parse(JSON.stringify(value)) as T
}

function isMessageRole(value: unknown): value is AssistantMessageRole {
  return value === 'user' || value === 'assistant' || value === 'system'
}

function normalizeMessage(value: unknown): AssistantMessage | null {
  if (!value || typeof value !== 'object') return null
  const candidate = value as Partial<AssistantMessage>
  if (typeof candidate.id !== 'string' || !isMessageRole(candidate.role) || typeof candidate.content !== 'string') {
    return null
  }
  const content = candidate.content.trim()
  if (!content) return null
  return {
    id: candidate.id,
    role: candidate.role,
    content,
    createdAt: typeof candidate.createdAt === 'number' && Number.isFinite(candidate.createdAt)
      ? candidate.createdAt
      : Date.now()
  }
}

function normalizeSession(value: unknown): AssistantSession | null {
  if (!value || typeof value !== 'object') return null
  const candidate = value as Partial<AssistantSession>
  if (typeof candidate.id !== 'string' || typeof candidate.title !== 'string') return null
  const messages = Array.isArray(candidate.messages)
    ? candidate.messages.map(normalizeMessage).filter((message): message is AssistantMessage => message !== null)
    : []
  const createdAt = typeof candidate.createdAt === 'number' && Number.isFinite(candidate.createdAt)
    ? candidate.createdAt
    : Date.now()
  const updatedAt = typeof candidate.updatedAt === 'number' && Number.isFinite(candidate.updatedAt)
    ? candidate.updatedAt
    : createdAt
  const bookId = typeof candidate.bookId === 'string' && candidate.bookId.trim() ? candidate.bookId : undefined
  const summary = typeof candidate.summary === 'string' && candidate.summary.trim()
    ? candidate.summary.trim()
    : undefined
  return {
    id: candidate.id,
    title: candidate.title.trim() || DEFAULT_SESSION_TITLE,
    ...(bookId ? { bookId } : {}),
    messages,
    ...(summary ? { summary } : {}),
    createdAt,
    updatedAt
  }
}

function sortSessions(sessions: AssistantSession[]): AssistantSession[] {
  return sessions.slice().sort((a, b) => b.updatedAt - a.updatedAt)
}

async function readSessions(): Promise<AssistantSession[]> {
  await initDB()
  const record = await indexedDB.get<{ key: string; sessions?: unknown }>('metadata', ASSISTANT_SESSIONS_METADATA_KEY)
  if (!record || !Array.isArray(record.sessions)) return []
  return sortSessions(record.sessions.map(normalizeSession).filter((session): session is AssistantSession => session !== null))
}

async function writeSessions(sessions: AssistantSession[]): Promise<void> {
  await initDB()
  await indexedDB.put('metadata', {
    key: ASSISTANT_SESSIONS_METADATA_KEY,
    sessions: sortSessions(sessions).map(clone)
  })
}

function queueWrite(operation: () => Promise<void>): Promise<void> {
  writeQueue = writeQueue.then(operation, operation)
  return writeQueue
}

export async function getAssistantSessions(): Promise<AssistantSession[]> {
  return clone(await readSessions())
}

export async function createAssistantSession(input: CreateAssistantSessionInput = {}): Promise<AssistantSession> {
  const now = Date.now()
  const session: AssistantSession = {
    id: createLocalId(),
    title: input.title?.trim() || DEFAULT_SESSION_TITLE,
    ...(input.bookId?.trim() ? { bookId: input.bookId.trim() } : {}),
    messages: [],
    createdAt: now,
    updatedAt: now
  }
  await queueWrite(async () => {
    const sessions = await readSessions()
    await writeSessions([session, ...sessions])
  })
  return clone(session)
}

export async function updateAssistantSession(
  id: string,
  updates: Partial<Pick<AssistantSession, 'title' | 'bookId' | 'summary'>>
): Promise<AssistantSession> {
  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    const title = updates.title === undefined ? existing.title : updates.title.trim() || DEFAULT_SESSION_TITLE
    const next: AssistantSession = {
      ...existing,
      title,
      ...(updates.bookId === undefined
        ? (existing.bookId ? { bookId: existing.bookId } : {})
        : (updates.bookId.trim() ? { bookId: updates.bookId.trim() } : {})),
      ...(updates.summary === undefined
        ? (existing.summary ? { summary: existing.summary } : {})
        : (updates.summary.trim() ? { summary: updates.summary.trim() } : {})),
      updatedAt: Date.now()
    }
    result = next
    await writeSessions(sessions.map(session => session.id === id ? next : session))
  })
  return clone(result as AssistantSession)
}

export async function appendAssistantMessage(
  id: string,
  input: AppendAssistantMessageInput
): Promise<AssistantSession> {
  const content = input.content.trim()
  if (!isMessageRole(input.role)) throw new Error('ASSISTANT_MESSAGE_ROLE_INVALID')
  if (!content) throw new Error('ASSISTANT_MESSAGE_EMPTY')

  let result: AssistantSession | undefined
  await queueWrite(async () => {
    const sessions = await readSessions()
    const existing = sessions.find(session => session.id === id)
    if (!existing) throw new Error(`ASSISTANT_SESSION_NOT_FOUND:${id}`)
    const message: AssistantMessage = {
      id: createLocalId(),
      role: input.role,
      content,
      createdAt: typeof input.createdAt === 'number' && Number.isFinite(input.createdAt)
        ? input.createdAt
        : Date.now()
    }
    result = { ...existing, messages: [...existing.messages, message], updatedAt: Date.now() }
    await writeSessions(sessions.map(session => session.id === id ? result as AssistantSession : session))
  })
  return clone(result as AssistantSession)
}

export async function deleteAssistantSession(id: string): Promise<void> {
  await queueWrite(async () => {
    const sessions = await readSessions()
    await writeSessions(sessions.filter(session => session.id !== id))
  })
}

export async function clearAssistantSessions(): Promise<void> {
  await queueWrite(() => writeSessions([]))
}

/**
 * Keep a compact, message-boundary-safe history for a model request. The
 * persisted conversation remains complete; this only limits the prompt.
 */
export function compactAssistantHistory(messages: AssistantMessage[], maxChars = 12000): AssistantMessage[] {
  if (maxChars <= 0) return []
  const compacted: AssistantMessage[] = []
  let used = 0
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index]
    const cost = message.content.length
    if (compacted.length > 0 && used + cost > maxChars) break
    if (cost > maxChars && compacted.length === 0) {
      compacted.unshift({ ...message, content: message.content.slice(-maxChars) })
      break
    }
    compacted.unshift(message)
    used += cost
  }
  return clone(compacted)
}
